### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by sanjitgroverincedo** [noahjohn9259/react-clear-cache#27]
While creating build, it is giving error:

On running  - npm run build

npm run generate-build-meta
> ./node_modules/react-clear-cache/bin/cli.js

'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by spriggsy83** [comment]
I solved this by switching the prebuild script to the following:  
```
"scripts": {  
   ...  
    "prebuild": "node ./node_modules/react-clear-cache/bin/cli.js"  
  },
```  
With this, running `npm run prebuild` works.

**Comment by noahjohn9259** [comment]
thanks @spriggsy83
