### ISSUE TITLE
App tries to fetch Meta.json when user is offline

### ISSUE THREAD

**Issue by Akinmyde** [noahjohn9259/react-clear-cache#28]
I am using the package with an app that can be accessed when the user is offline and I noticed that when the user is offline, the app tries to load the meta.json file.

I don't want this behaviour when users are offline. I only want to load the file only when the user is online.

**Comment by noahjohn9259** [comment]
hi @Akinmyde, sorry for the delay and thank you for pointing that out. Please install the latest version.

**Comment by noahjohn9259** [comment]
Please re-open if it doesn't work.

**Comment by Akinmyde** [comment]
It works with version 1.0.11. Thanks, @noahjohn9259
