### ISSUE TITLE
In IE getting reloded continuously when set true for auto property

### ISSUE THREAD

**Issue by vnaveed** [noahjohn9259/react-clear-cache#3]
In IE getting reloded continuously when set true for auto property

**Comment by Joohansson** [comment]
I want to test this, how do you set that property?

**Comment by lapwil** [comment]
I had the same issue with Chrome, I had to unset the auto

**Comment by noahjohn9259** [comment]
hi guys, i am gonna look into this.

**Comment by noahjohn9259** [comment]
@Joohansson fixed with latest patch version.
