### ISSUE TITLE
Unexpected token | in JSON at position 13

### ISSUE THREAD

**Issue by Akinmyde** [noahjohn9259/react-clear-cache#33]
I noticed an unexpected token | in JSON at position 13 and some other unexpected token issue with a submodule `use-persisted-state` that is been used in react-clear-cache. 

Here is a screenshot of my sentry tracker. 
<img width="1347" alt="Screenshot 2020-12-17 at 10 44 30" src="https://user-images.githubusercontent.com/26759774/102471293-5658f380-4055-11eb-88ba-99bad4544f03.png">

**Comment by nucab** [comment]
This seems to be an isolated issue. Closing this issue for now.

**Comment by tejaswitandel** [comment]
I am also facing this issue.
