### ISSUE TITLE
Failed to execute 'delete' on 'CacheStorage': Illegal invocation

### ISSUE THREAD

**Issue by atar-axis** [noahjohn9259/react-clear-cache#34]
https://stackoverflow.com/questions/65350515/failed-to-execute-delete-on-cachestorage-illegal-invocation

---

I would like to call emptyCacheStorage from a notistack action button. Therefore I did something similar to the following codesandbox: https://codesandbox.io/s/wonderful-satoshi-2ukly?file=/src/App.js

Just ignore(?) the error message about the JSON thingy, I don't know how to get rid of it at development.

For documentation, the code is something like
```
import React from "react";
import { useClearCache } from "react-clear-cache";
import { useSnackbar, SnackbarProvider } from "notistack";
import Button from '@material-ui/core/Button';

import "./styles.css";

function Snacks() {
  const { isLatestVersion, emptyCacheStorage } = useClearCache();
  const { enqueueSnackbar, closeSnackbar } = useSnackbar();

  const message = "Your notification here";
  const action = key => (
    <>
        <Button
        onClick={() => { emptyCacheStorage() }}>
            'clear'
        </Button>

    </>
);
  // enqueue persistent snackbar
  enqueueSnackbar(message, {
    persist: true,
    action
  });

  return null;
}

export default function App() {
  return (
    <SnackbarProvider maxSnack={3}>
      <Snacks />
    </SnackbarProvider>
  );
}
```
My question:

What does `Failed to execute 'delete' on 'CacheStorage': Illegal invocation` mean and how to get rid of it?

**Comment by atar-axis** [comment]
found the problem, I needed to use `import { useClearCacheCtx } from 'react-clear-cache'` instead of `import { useClearCache } from 'react-clear-cache';`

**Comment by atar-axis** [comment]
nope, that wasn't the problem unfortunately... :(

**Comment by atar-axis** [comment]
still the same issue: https://codesandbox.io/s/wonderful-satoshi-2ukly?file=/src/App.js

**Comment by atar-axis** [comment]
is it possible that `isLatestVersion` MUST be `false` in order to `emptyCacheStorage` to work correctly?

**Comment by LuizMaestri** [comment]
For me, the code works in development but when in production I have the same problem. 
I think it's something with production's build. 

```
import Snackbar from '@material-ui/core/Snackbar';
import Alert from 'components/alert';
import Portal from 'components/portal';
import { useClearCache } from 'react-clear-cache';
import { useIntl } from 'react-intl';

const Cache = () => {
    const { isLatestVersion, emptyCacheStorage } = useClearCache();
    const anchorOrigin = { vertical: 'top', horizontal: 'center' };
    const intl = useIntl();
    console.log(isLatestVersion);
    return (
        <Portal>
            <Snackbar
                anchorOrigin={anchorOrigin}
                open={!isLatestVersion}
                onClick={() => emptyCacheStorage()}
            >
                <Alert severity="warning">
                    {intl
                        .formatMessage({ id: 'cache-invalid.warning' })
                        .split('\n')
                        .map((text, index) => (
                            <p key={index}>{text}</p>
                        ))}
                </Alert>
            </Snackbar>
        </Portal>
    );
};

export default Cache;
```

**Comment by noahjohn9259** [comment]
hi @atar-axis, you might forgot to generate the version file. Try to run the `generate-build-meta` first and run it again.
