### ISSUE TITLE
deprecated  window.location.reload(true);

### ISSUE THREAD

**Issue by atar-axis** [noahjohn9259/react-clear-cache#35]
While trying to find the problem of another issue I found the following line in your code:

`window.location.reload(true);`
https://github.com/noahjohn9259/react-clear-cache/blob/cfa13bbf437a11572c618a0e43d09a1a128b387f/src/index.tsx#L69

Unfortunately passing `true` to `reload` is deprecated as far as I know.

**Comment by nucab** [comment]
thank you for pointing out @atar-axis .. well appreciated it!

**Comment by nucab** [comment]
check out the new version. thanks!
