### ISSUE TITLE
Get latest version string using context API

### ISSUE THREAD

**Issue by carneirocorp** [noahjohn9259/react-clear-cache#40]
It is possible to get a string using context API ?

There are only one example using hooks where the latest version get exposed but my application is not using this approach.

**Comment by noahjohn9259** [comment]
You can use the hook `useClearCacheCtx`. It returns an object similar with `useClearCache`.

**Comment by carneirocorp** [comment]
I'm sorry but i can see the property with latestVersion string on this similar object... it exists ?
