### ISSUE TITLE
Usage with localStorage.clear

### ISSUE THREAD

**Issue by lapwil** [noahjohn9259/react-clear-cache#8]
Hi,

I'm curretly working on a projet and I use your clear-cache.

Some users had issues with their cache, using chromium on a surface, so I added a functionality for them, a button that would clear the localStorage cache and update their cachestorage afterwards.

I used it like so 
/buttonComponent.jsx
```
resetApp = emptyCacheStorage => event => {
  event.preventDefault();
  localStorage.clear();
  emptyCacheStorage();
}

[...]

render() {
  return (
    <ClearCache>
      { 
         ({emptyCacheStorage) => 
           <Button onClick={this.resetApp(emptyCacheStorage)}>Foo</Button>
      }
    </ClearCache>
  }
}
```

But when I use it, the first time, il completely clears the storage, so versions are different.

If I click again, the version matches the latest version.

And it keeps toggling each time I call my function.

Thanks

**Comment by noahjohn9259** [comment]
this is fixed with the latest version @lapwil .
